### ISSUE TITLE
Assets distribution

### ISSUE THREAD

**Issue by RobertZenz** [egordorichev/LastTry#13]
Are you distributing assets from Terraria, because the note above the license makes it sound you does?

**Comment by egordorichev** [comment]
Thanks for your notice. Were are using a few sprites right now, but I'm looking for an artist, how can draw terraria-looking sprites for us. Other wise, we will use one of the Texture Packs for Terraria.

**Comment by RobertZenz** [comment]
I'm pretty sure that distributing the assets of Terraria is a copyright violation, unless you have written permission to do so. So you want to get rid of those.

**Comment by egordorichev** [comment]
Ok, sure.

**Comment by i-need-to-tell-you-something** [comment]
I read the Terraria license agreement and yes it forbids using its assets.
Im guessing that the easiest (and least resource-consuming) way would be to use one of the texture packs for Terraria (as you said). You could possibly implement a way for players to introduce the original Terraria assets to this engine (if they have legally acquired Terraria). The VCMI (Heroes 3 engine) project uses that kind of loophole for the assets if im not mistaken.

**Comment by egordorichev** [comment]
Thank you! We are currently using a texture pack. Loading XNA images is a good idea, but this shouldn't be done now, because we will need to convert them to png every time we need to modify them.

**Comment by RobertZenz** [comment]
Just as a note, I just saw that you're still using the "Terraria tree" in the logo, you might want to get rid of that one, too.

**Comment by egordorichev** [comment]
Ah, ok.

**Comment by egordorichev** [comment]
@Col-E or @logotie, can you please do that? Cant commit right now.
