### ISSUE TITLE
asm-5.2.4.jar

### ISSUE THREAD

**Issue by backendr** [egordorichev/LastTry#14]
I am adding `maven` dependency management to the project.
I see that you have `asm-5.2.4.jar` as a lib, though looking online the highest I can find is `5.2`.
https://mvnrepository.com/artifact/org.ow2.asm/asm

The problem is that 
```
<dependency>
        <groupId>org.ow2.asm</groupId>
        <artifactId>asm</artifactId>
        <version>5.2</version>
</dependency>
```
**Doesnt** contain `ClassAdapter`:`java.lang.NoClassDefFoundError: org/objectweb/asm/ClassAdapter`

Where did you find this artifact?

**Comment by egordorichev** [comment]
Some where on the web. Will replace it with `asm-5.2.jar`

**Comment by egordorichev** [comment]
Fixed by https://github.com/egordorichev/LastTry/commit/0afa577f5b9ea9cc7e2f5dd5b8b8b98bcbd6a278

**Comment by egordorichev** [comment]
Also, @backendr, can you setup build tests some where? For example on https://travis-ci.org. Thanks!

**Comment by backendr** [comment]
Does your build still work after the change in 0afa577?

**Comment by egordorichev** [comment]
On my computer, it does.
