### ISSUE TITLE
What is GhostMod.jar?

### ISSUE THREAD

**Issue by backendr** [egordorichev/LastTry#15]
Would you be able to provide some information about this jar?

**Comment by Col-E** [comment]
https://github.com/egordorichev/LastTry/tree/master/assets/mods

Its in the assets folder and is loaded at runtime by the mod loader. It adds a keybind (G) that toggles ghost mode (no-clip) for the player.

**Comment by backendr** [comment]
Further questions:

Why does it contain:
 + org/egordorichev/ghostmod/GhostMod.jar
 + org/lasttry/* (Looks like a copy of all the project class files)
 + org/intellij/* (class files)
 + org/jetbrains/* (class files)
 + org/keplerproject/* (class files)
 + org/lwjgl/* (class files)
 + org/newdawn/slick/* (class files)
 + the entire net folder

**Comment by backendr** [comment]
It feels like some of this can be cleaned up and the jar can be remade?

**Comment by egordorichev** [comment]
Hm, It is Mod dependencies. I don't think they can be removed. I will read about that.

**Comment by backendr** [comment]
How is this jar being built?
Where are the dependencies specified?
Any background info?

**Comment by egordorichev** [comment]
I've build it with my Intellij IDE. Using all dependencies from LastTry, and a packed LastTry.jar

**Comment by egordorichev** [comment]
Ok. Fixed. I've build a new one without any extra java classes. Only `GhostMod.class` and `GhosMod$1.class`
