### ISSUE TITLE
Entity doesn't enter IDLE state after moving

### ISSUE THREAD

**Issue by CameronDowner** [egordorichev/LastTry#2]
This is an issue with in the Entity.java class & is indicated in the comment on [line 123](https://github.com/egordorichev/LastTry/blob/master/src/org/egordorichev/lasttry/entity/Entity.java#L123).

I think this is being caused by [line 95](https://github.com/egordorichev/LastTry/blob/master/src/org/egordorichev/lasttry/entity/Entity.java#L95), which is multiplying the x velocity by 0.8, which means it never actually gets to zero thus never satisfying the condition on [line 122](https://github.com/egordorichev/LastTry/blob/master/src/org/egordorichev/lasttry/entity/Entity.java#L122)

**Comment by Col-E** [comment]
I've fixed this on my fork by checking if the absolute value of the x-axis motion is below a certain level, then setting it to zero.

Plus I also [documented the class](https://github.com/Col-E/LastTry/blob/master/src/org/egordorichev/lasttry/entity/Entity.java)

**Comment by egordorichev** [comment]
Yep, Thanks! Will fix that today!
