### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#20]
Just now the `README.md` is completely unuseful. We need to fix that. New structure:

- **LARGE Screenshot or logo**  
- Description
- Goals
- Installation
- Contributing
- License (optional, maybe just a link to the file)

**Comment by Col-E** [comment]
How about instead of forcing viewers to load a large image we have a small collage image but then link to an Imgur album?

**Comment by egordorichev** [comment]
Awesome idea.

**Comment by egordorichev** [comment]
Updated README, without logo yet.
