### ISSUE TITLE
Java doc and java code style

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#30]
@Col-E, I see, that my java doc style is not perfect (in fact, it is first time I use it a lot). So can you figure out the code style and java doc style for the project. Is this a good style? 

```java
        /**
	 * Handles window resize
	 * @param width new window width
	 * @param height new window height
	 */
	@Override
	public void resize(int width, int height) {
		super.resize(width, height);

		viewport.update(width, height);
		camera.update();
	}
```

**Comment by Col-E** [comment]
All you really need to do for javadoc is just follow [oracle's post](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html). You don't have to be super verbose like some of the examples it gives, but aside from that it's spot on.
