### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#31]
All text is currently hardcoded to the game. Probably, we need a basic Language class, so we can easily change the game language.  Something like this should work:

```java
public class Language {
   public static void load(String locale) {

   }

   public static String dirt = "dirt".
}
```

And so on.

**Comment by Col-E** [comment]
We could also use the [default java il8n](https://docs.oracle.com/javase/tutorial/i18n/intro/quick.html).

**Comment by egordorichev** [comment]
Or another options is something like that:

```java
class Strings {
    public static String greenSlime = "";
}

...
Somewhere load those strings, for example, from json
...

System.out.println("Green slime is " + Strings.greenSlime);
```

**Comment by PeterWathall** [comment]
I've tried out the default system and it seems very easy to use so I'm going to try and implement it.

**Comment by egordorichev** [comment]
Great, thank you!

**Comment by PeterWathall** [comment]
I'm just moving over all of the current text but adding a new language will just involve creating a text file for that language.

I need Language.load() to be called straight away after the game starts, where should I put it?

**Comment by egordorichev** [comment]
Put it in the SplashState.java or in the LastTry.java, if it won't take much time to load.

**Comment by PeterWathall** [comment]
There's an absolute ton of text to add to the file but the system is working already

**Comment by egordorichev** [comment]
Great! How is the text file organized? Is it a json?

**Comment by egordorichev** [comment]
I will be unable to commit for two days, but don't worry, will return to the development on monday.

**Comment by PeterWathall** [comment]
Ok.

I'll commit what I've done so far and you can see if you think it's a viable system.

**Comment by egordorichev** [comment]
Great!
