### ISSUE TITLE
Broken hair

### ISSUE THREAD

**Issue by PeterWathall** [egordorichev/LastTry#39]
The player's hair flickers, appearing and disappearing regularly as you walk along the ground. But this doesn't happen while moving through the air, it only happens during the walking animation.

On the main branch the hair was sometimes moving towards the player's feet too so I removed this line from org.egordorichev.lasttry.entity.player.PlayerRenderer:

`pixmap.drawPixmap(hair, 0, 748);`

and it stopped happening, I have no idea what that line was for but removing it didn't seem to break anything.

**Comment by egordorichev** [comment]
![playerhair1](https://cloud.githubusercontent.com/assets/7851390/24705687/bb79e40a-1a15-11e7-8c04-70b966f8d3a3.png)

Here is the hair.

![playerhead](https://cloud.githubusercontent.com/assets/7851390/24705702/c5b90ab8-1a15-11e7-8e26-2e0000544309.png)

And here is the head.

**Comment by egordorichev** [comment]
Fixed.
