### ISSUE TITLE
Drawing both blocks and walls slows my FPS

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#4]
This fragment in TileData.java is very strange:

```
		if (wall != null) {
			wall.renderWall(this, x, y);
		}
		if (block != null) {
			block.renderBlock(this, x, y);
		}
```

If I run it and using the Ghost mode and go down into the earth a bit, my FPS drops. To 30. 
But if I replace it with this code:

```
		if (wall != null) {
			wall.renderWall(this, x, y);
			wall.renderWall(this, x, y);
		}
```

or even with this:

```
		if (block != null) {
			block.renderBlock(this, x, y);
			block.renderBlock(this, x, y);
		}
```

All works fine. What is the catch?

**Comment by backendr** [comment]
I can enter ghost mode and go down to `Y:10000` with no frame drops.
Is this still an issue?

**Comment by egordorichev** [comment]
Maybe this is my computer issue (i don't have a video card). So if it doent lag at your PC, that not more an issue. What is your hardware?

**Comment by backendr** [comment]
2015 MacbookPro

**Comment by egordorichev** [comment]
Ok. Then this is my problem.

**Comment by Col-E** [comment]
Well there may also be people with your same problem. It would be nice to have at least an option for rendering cut-backs for low-end computers.

**Comment by egordorichev** [comment]
Strange, but in libgdx this bug is not fixed for me...
