### ISSUE TITLE
World save/load improvement

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#41]
According to the, https://github.com/egordorichev/LastTry/pull/40 we **must impove** save system for the world. Added to **todo** list https://trello.com/c/SG1TeEc6/26-make-world-file-size-smaller-a-ton.

Probably, we should implement chunks system. If we will use chunks method, will we need to create infinite worlds?

**Comment by PeterWathall** [comment]
I've been wondering, why is the world stored in memory as a linear array rather than just making it two dimensional so blocks can be accessed directly with their x and y?

**Comment by egordorichev** [comment]
Because to alloc 2d array you need to call new width times. But when you use 1d array, you need only one alloc call.

**Comment by egordorichev** [comment]
And in the new system I plan to use the same technic, but splited into chunks. But will help you, we always can make a array wrapper.

**Comment by PeterWathall** [comment]
A 2d array in java is done like this:

`int[][] data = new int[height][width]`

**Comment by egordorichev** [comment]
So here is the development plan:
- [ ] **1D array class wrapper** If we need it
- [ ] **Chunk** Manages constant amount of blocks
- [ ] **ChunkProvider** Loads/saves chunks, updates corruption
- [ ] **ChunkManager** Stores all of the chunks, calls Chunk Provider if needed
- [ ] **Update the world class**

Also, will we need infinite worlds?

**Comment by PeterWathall** [comment]
Apparently terraria doesn't have an infinite world because they keep the entire map in memory so that they can make trees grow and stuff so we don't really need one but I think that we could have one if we wanted. 

Instead of keeping all of the map in memory we could just increase a time variable on each chunk that isn't loaded and when the chunk gets loaded it updates everything that changes with time like trees.

**Comment by egordorichev** [comment]
Ok, sure. Also, we should flip the y-axis of the game logic. When we moved to libgdx, we inverted the drawing y-axis, but not the logic one. So now, the world 0:0 should be at bottom right for simplicity of calculations.

**Comment by egordorichev** [comment]
Done in https://github.com/egordorichev/LastTry/pull/58 .
