### ISSUE TITLE
Bundle with language not found

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#45]
Just returned from a trip, pulled and run the new source:

```
LastTry had crashed!
-------------------
LastTry had stopped running, because it encountered a problem.

Please, copy and report the entire text to email egordorichev@gmail.com or
submit an issue https://github.com/egordorichev/LastTry/issues


--- BEGIN ERROR REPORT ---
LastTry version: v.0.3
OS: Linux (amd64) version 3.18.9-gentoo
Java version: 1.8.0_72, Oracle Corporation
Java VM version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Java VM flags: 0 total; 
Memory: 222811528 bytes (212 MB) / 243269632 bytes (232 MB) up to 3596091392 bytes (3429 MB)
Exception cause: java.util.MissingResourceException: Can't find bundle for base name language, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at org.egordorichev.lasttry.language.Language.load(Language.java:10)
	at org.egordorichev.lasttry.LastTry.create(LastTry.java:106)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
--- END ERROR REPORT ---
```
Something with language is missing.

**Comment by PeterWathall** [comment]
I'm not getting that in the current build but in testing it I did find another bug and fix it.

Are you using the latest version with all of my commits?

Is there a file in /core/assets called "language_en_US.properties"?

**Comment by egordorichev** [comment]
Yep, it is.

**Comment by PeterWathall** [comment]
I'm not getting this error so I don't know what to say.

The error means that it can't find language_en_US.properties and I was getting this before because it was in a source folder rather than in assets so the build wasn't including it in the jar.

**Comment by egordorichev** [comment]
Are you sure, that you've pushed all of the files, you added? Maybe you should check the latest build with your own.

**Comment by PeterWathall** [comment]
Everything is pushed and all the files are right on here so it's something else.

If you upload your built jar I'll decompile it and see if there's anything different

**Comment by egordorichev** [comment]
Can't upload it here, will upload in the repo.

**Comment by egordorichev** [comment]
Strange, in jar all works.

**Comment by egordorichev** [comment]
To witch directory is you working folder set?

**Comment by PeterWathall** [comment]
It's working fine for me, how were you trying to run it before?

**Comment by egordorichev** [comment]
I've compiling it with Intellij IDEA, the working directory is set to `core/assets/`

**Comment by PeterWathall** [comment]
Oh right I'm using netbeans and just getting it to run the gradle dist build

**Comment by egordorichev** [comment]
Ok, please, notify me with the result.
