### ISSUE TITLE
Infinite jumping

### ISSUE THREAD

**Issue by PeterWathall** [egordorichev/LastTry#46]
If you hold jump with a block above you, it lets you hover there forever. You can abuse this to basically fly upwards.

It's actually quite a fun bug so you might not want to remove it.

![flying](https://cloud.githubusercontent.com/assets/9157578/24838775/c68cae16-1d46-11e7-823c-85a9b01ee785.gif)

**Comment by egordorichev** [comment]
Yes, it looks like the player climbs up ;) By the way, the work benches are not finished yet.

**Comment by egordorichev** [comment]
It happens because the physic body y-velocity is 0 and player can jump again.

**Comment by PeterWathall** [comment]
It is somewhat fixed but you can still occasionally do it because of the coordinate system being janky

**Comment by egordorichev** [comment]
Will flip in in the new chunk system.

**Comment by PeterWathall** [comment]
That is a bit silly but that's not the problem I'm talking about.

The problem is that I'm getting the coordinate of the player as an integer (getGridX) but the player can be between coordinates in a floating point so checking the block above their gridx isn't necessarily the block they are directly beneath allowing them to still jump if at the very edge of a block.

**Comment by egordorichev** [comment]
Ok, but that can be easily fixed.

**Comment by Col-E** [comment]
Fixed as of https://github.com/egordorichev/LastTry/pull/78
