### ISSUE TITLE
Player texture being cut off

### ISSUE THREAD

**Issue by PeterWathall** [egordorichev/LastTry#47]
The top of the texture isn't being rendered, it's like the player is in a box that is too small and anything outside the box is cut off.

I'm guessing there actually is a box somewhere in the code and that it's too small.

![cut off](https://cloud.githubusercontent.com/assets/9157578/24932266/a62b495c-1f08-11e7-8d08-4a0858f1991c.PNG)

**Comment by egordorichev** [comment]
Yes, yes, those hair textures... they need my attention. By the way, did the bundle bug go away on your side?

**Comment by PeterWathall** [comment]
I never had the bundle bug

**Comment by egordorichev** [comment]
So it compiles right? I still can't fix it.

**Comment by PeterWathall** [comment]
Are you using the gradle dist to compile into a jar and then running the jar?

**Comment by egordorichev** [comment]
When I compile to jar, all works fine. But when I compile it using ide just to classes, it fails with exception at top.

**Comment by PeterWathall** [comment]
You have to actually build it so that it can find the language file

**Comment by egordorichev** [comment]
I **do** build it. But not into a jar. I just compile it to classes. Is it possible to find the budle without compiling to a jar?

**Comment by PeterWathall** [comment]
Maybe but I don't know

**Comment by egordorichev** [comment]
Will need to implement that, this will save us quite a lot of time.

**Comment by PeterWathall** [comment]
I think we should use the gitter so that issues don't get filled up with general chat

**Comment by egordorichev** [comment]
Fixed.

**Comment by Col-E** [comment]
Egor said its fixed, so closing.
