### ISSUE TITLE
World names containing spaces break the game

### ISSUE THREAD

**Issue by PeterWathall** [egordorichev/LastTry#48]
It can't handle them for some reason, it crashes and then crashes on startup if you don't remove the actual file

**Comment by PeterWathall** [comment]
Actually no I'm just being stupid it's because I'm on the other branch that doesn't work

**Comment by egordorichev** [comment]
But we still need to check world names and player names, so they can't be created with empty name.

**Comment by PeterWathall** [comment]
I'll make a new issue for that
