### ISSUE TITLE
Name Validation

### ISSUE THREAD

**Issue by PeterWathall** [egordorichev/LastTry#49]
It shouldn't be possible to have a blank world name or player name.

It should probably check for weird non alphanumeric characters too.

**Comment by logotie** [comment]
Started work on this:

https://github.com/egordorichev/LastTry/commit/f08d44c9c32e05eee35cde8319a5bcca5ab258a7

**Comment by logotie** [comment]
I added the functionality, based on:
Shows a red error message (preventing the user from entering a player/world name) to the user if:
Player name or World name is blank.
Player name or World name already exists.

Commit:
https://github.com/egordorichev/LastTry/commit/89282f4a8088dbf835a4ea915cdc16eb87759b67

Please let me know, if any improvements are needed.  

Functionality must be extended however to check for certain non alphanumeric characters.

**Comment by egordorichev** [comment]
Great! I think, this issue is closed now.
