### ISSUE TITLE
Spawn system

### ISSUE THREAD

**Issue by logotie** [egordorichev/LastTry#53]
**1: Get user's biome**

**2: Get 'spawn rate' & 'max spawns' of biome.**

**3: calculate the spawnRate(Spawn Rate, Max Spawns)**
{
1--- Check what events are active
If event has a hardcoded 'Max spawns', 'Spawn rate' &  'Monsters list' we call 'getTotalSpawnWeightOfActiveMonsters'

else
2--- Check time of day
Increase/decrease spawn rate

3 -- Check items in the environment
Increase/decrease spawn rate

4 -- then call getTotalSpawnWeightOfActiveMonsters

5 - then call '5'
}

_function getTotalSpawnWeightOfActiveMonsters()_
Calculate player spawn area.
Go through enemies and check if they are in player area.
Generate list of enemies in player area.
Calculate and return total spawn weight of monsters in player area.

**4 -- Receives spawn rate, max spawns, spawn weight of active monsters.**
If spawn weight of active monsters greater than max spawns - exit
else
calculate difference between max spawns and spawn weight of active monsters
based on the difference, we apply a multiplier to the spawn rate.
A lot of monsters already existing, we reduce spawn rate
Not a lot of monsters, we increase spawn rate

**5 -- Gets a random number and compares to spawn rate, then returns true**

**6** -- SUCCESSFUL 
--- Check if event is active and check if monsters exist for event.
else
--- Get list of eligible monsters based on Biome
--- Get coefficient from previous calculation.
--- Choose monster randomly
--- Call getValidCoOrdinates()
--- Pass co ordinates and monster, to spawn function.

_function getValidCoOrdinates()_
Returns valid co ordinates for spawning

**7 -- Pass entity and co ordinates to 'spawn' function outside of class.**

**Comment by egordorichev** [comment]
Great job! Maybe, enemy should have canSpawn() method?

**Comment by logotie** [comment]
Yeah that sounds really good.  The enemies will know when they can spawn, rather than the events.  Thanks
