### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by logotie** [egordorichev/LastTry#63]
Addition of Lighting to LastTry.
 
Lighting from sources, such as torches and Sun.

**Comment by logotie** [comment]
http://www.java-gaming.org/index.php?topic=28685.0

**Comment by Col-E** [comment]
[WIP](https://my.mixtape.moe/uvujow.mp4)

Isn't super great, but its a start.

**Comment by egordorichev** [comment]
Implemented by @Col-E.
