### ISSUE TITLE
Entities become invisible when located to the left of the player

### ISSUE THREAD

**Issue by Col-E** [egordorichev/LastTry#66]
![Example](https://my.mixtape.moe/uhuqjn.gif)

Is this part of the TODO list? It applies for all entities, slimes are just the first thing I noticed.

* ["Slimes are bugging"](https://trello.com/c/9vckw98j/87-slimes-are-bugging)

Also on a kinda related slime note [sometimes when you kill something you can attack the place where it last was](https://my.mixtape.moe/wzxgtz.png). This hitbox doesn't despawn.

**Comment by egordorichev** [comment]
Yay, @Col-E! Welcome back :) Thanks for the spot! We currently have some issues with migrating from `AssetManager` to `AssetManager` + `TextureAtlas`. This will be fixed in a few days.

**Comment by Col-E** [comment]
> This will be fixed in a few days.

Ok, cool!

> You should use dev one, to get latest code.

Just did master out of habit. Will pull dev in a minute or two.

> Also, if you wan't to, I can add you to trello. 

Joined with the invite link.

**Comment by egordorichev** [comment]
Thanks, @Col-E! Check the gitter, i've posted some useful info.

**Comment by egordorichev** [comment]
So, found the bug source:

```
		Rectangle camera = new Rectangle(Camera.game.position.x - 16, Camera.game.position.y - 16, Gdx.graphics.getWidth() + 32, Gdx.graphics.getHeight());

		for (Entity entity : this.entities) {
			if (entity.physics.getHitbox().intersects(camera)) {
				entity.render();
			}
		}
```

**Comment by egordorichev** [comment]
```java
		int halfWidth = Gdx.graphics.getWidth() / 2;
		int halfHeight = Gdx.graphics.getHeight() / 2;

		Rectangle camera = new Rectangle(Camera.game.position.x - 16 - halfWidth, Camera.game.position.y - 16 - halfHeight,
			Camera.game.position.x + halfWidth + 32, Camera.game.position.y + halfHeight + 32);

		for (Entity entity : this.entities) {
			if (entity.physics.getHitbox().intersects(camera)) {
				entity.render();
			}
		}
```
