### ISSUE TITLE
Sometimes when you kill something you can attack the place where it last was. 

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#67]
> Also on a kinda related slime note sometimes when you kill something you can attack the place where it last was. This hitbox doesn't despawn.

@Col-E, found this bug.

**Comment by Col-E** [comment]
Why the `wontfix` label? Also, a picture of the issue:

![img](https://my.mixtape.moe/wzxgtz.png)

**Comment by egordorichev** [comment]
It looks like it is fixed now.
