### ISSUE TITLE
Attack hitboxes do not reflect what's being shown on-screen

### ISSUE THREAD

**Issue by Col-E** [egordorichev/LastTry#70]
Take this [clip](https://my.mixtape.moe/ctjwrr.mp4) for example. I have 2 zombies. One is behind a wall and I am looking away from the wall. When I click it behaves as if I'm attacking it.

**Comment by egordorichev** [comment]
Hm, I don't think, this is an issue. The pickaxe can hit them, right? And again, this is a game. Will leave this open for now.

**Comment by Col-E** [comment]
The issue should be an easy fix. As it stands the attack hitbox seems to just be the player's hitbox. All that needs to be done is to shift the hitbox based on the direction the player's aiming.

**Comment by egordorichev** [comment]
Yeah, the attack hitbox must be not the player hitbox, but the hitbox of the tool.
Current variant is a template.

**Comment by Col-E** [comment]
This was fixed in https://github.com/egordorichev/LastTry/pull/73
