### ISSUE TITLE
Chunk with changes can be reset

### ISSUE THREAD

**Issue by Col-E** [egordorichev/LastTry#79]
I was building a test ground for something and all of a sudden the terrain to reset to what it had looked like when I loaded up the game.

**Comment by egordorichev** [comment]
Did the map reset? Can't get, what yo mean.. If it reseted, that means, it did not save.

**Comment by Col-E** [comment]
Just sat around on a map until it did it again. [Heres the video](https://my.mixtape.moe/obvlqh.mp4)

**Comment by egordorichev** [comment]
Hm, why do you use ash in world gen, and not ebonstone and ebonsand? They are analogs for crimston and crimsand....

**Comment by egordorichev** [comment]
Also, sorry for messing up issues, but the Kindle wony open gitter chat. One thing you'va asked in InventorySlot:swapItems

> Why not return null?

Because item, that is returned, is set to inventory current. Hm, also, we should move logic with comparing item types inside of that method.

**Comment by Col-E** [comment]
It was just for resting real quick. I just pocked random blocks.

**Comment by egordorichev** [comment]
Wow, just saw the video. I think, that's the GC bug.

**Comment by egordorichev** [comment]
Fixed. Chunks where not saving on gc.
