### ISSUE TITLE
Setting up the initial lightmap doesn't unload chunks after completion

### ISSUE THREAD

**Issue by Col-E** [egordorichev/LastTry#84]
The idea is to pre-bake lighting initially so runtime updates will be small. So loading the chunks should happen. What should happen next is a step that unloads all chunks after setting up the world's light. Then when the player spawns in everything will behave as intended.

**Comment by egordorichev** [comment]
This system is not so optimized. You can do the same thing, but for chunk, and not the whole world. Also, current light system counts only neighbors, and the light level doesn't look deep.

**Comment by Col-E** [comment]
Yeah the entire system is a heavy WIP.

**Comment by Col-E** [comment]
The system no longer has a pre-bake design. This is irrelevant now.
