### ISSUE TITLE
Strange Dropped Item behavior

### ISSUE THREAD

**Issue by egordorichev** [egordorichev/LastTry#88]
![1 1](https://user-images.githubusercontent.com/7851390/26966789-41a13ad0-4d04-11e7-987e-5acc152c6d78.gif)

Did not see this happening before..

**Comment by Col-E** [comment]
Well, I can say for certain something has changed since I last committed 😕 
I'll check it out.

**Comment by Col-E** [comment]
Fixed https://github.com/egordorichev/LastTry/pull/89
