### ISSUE TITLE
Players have the same spawn point in all worlds.

### ISSUE THREAD

**Issue by Col-E** [egordorichev/LastTry#98]
The spawn point is handled in the player data, and is not different in each world

> In `world_a` spawn is in a valley. In `world_b` the same spot is inside a cliff. The player spawn is oriented around `world_a`, so spawning in a cliff in `world_b` occurs, instead of being placed on top of the cliff.

**Solution**: Spawn is handled by the world, not the player.

**Comment by egordorichev** [comment]
Hmm, I guess, the player should spawn in the center of the world, right? We only need to manage y-axis.

**Comment by Col-E** [comment]
Y-axis management done in the pull I'm working on.

**Comment by Col-E** [comment]
Resolved in https://github.com/egordorichev/LastTry/pull/103
